server:
  port: 8080

spring:
  application:
    name: rest
  profiles:
    active: test
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:h2:./db_test;MODE=MySQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: yakmatwin3652@gmail.com # Gmail 계정 입력
    password: ${SPRING_MAIL_PASSWORD} # 생성한 앱 비밀번호 입력
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.orm.jdbc.extract: TRACE
    org.springframework.transaction.interceptor: TRACE